### ISSUE TITLE
Script do not suspend when there are no scheduled recordings

### ISSUE THREAD

**Issue by kamiKAC** [git-developer/autosuspend#22]
Great script!

When there is no scheduled recordings script do not suspend at all.

```
Aug 26 09:25:09 mediaserver systemd[1]: Starting Autosuspend script...
Aug 26 09:25:09 mediaserver autosuspend[5777]: Fetched next 0 upcoming recordings from Tvheadend
Aug 26 09:25:09 mediaserver autosuspend[5788]: AUTO SUSPEND CAUSED
Aug 26 09:25:09 mediaserver autosuspend[5789]: Suspend method: poweroff
Aug 26 09:25:09 mediaserver autosuspend[5798]: Fetched next 0 upcoming recordings from Tvheadend
Aug 26 09:25:09 mediaserver autosuspend[5799]: No wake up time scheduled. Activity scripts may be added to '/etc/autosuspend.d/activities'
Aug 26 09:25:09 mediaserver autosuspend.sh[5704]: date: invalid date '@'
Aug 26 09:25:09 mediaserver autosuspend[5803]: Aborting suspend because wakeup time is in the past
Aug 26 09:25:09 mediaserver autosuspend.sh[5704]: The autosuspend script returned exit code 2, see the system log for details
```

I should schedule wakeup for let's say two days from now and suspend or suspend forever.

Best regards

**Comment by git-developer** [comment]
When no wakeup time can be determined (because no scheduled recordings and no other activities exist), the system does not shut down. This behavior is by design because it may be difficult or impossible to boot a remote server that is shut down and doesn't wake up on its own.

If you'd like your system to shutdown and wakeup in 2 days, you can create a small [activity script](https://github.com/git-developer/autosuspend/tree/master/etc/autosuspend.d/activities) for that task.

**Comment by git-developer** [comment]
You may want to check out the [develop](https://github.com/git-developer/autosuspend/tree/develop) branch where you can set the configuration variable `SUSPEND_WITHOUT_WAKEUP=yes` to change this behavior. Please have a try and report back.

**Comment by git-developer** [comment]
Issue closed due to missing feedback.
