### ISSUE TITLE
EPG subscription prevents autosuspend

### ISSUE THREAD

**Issue by malvinas2** [git-developer/autosuspend#4]
Hello, 

I don't know why, but the actualization of EPG over-the-air triggered by TVHeadend takes several hours here, which prevents autosuspend as there still is one subscription. 
Is it possible to add an option so that the autospend-script ignores / doesn't consider EPG subscription ? 

[https://i.imgur.com/KnpN0r1.png](https://i.imgur.com/KnpN0r1.png)

**Comment by git-developer** [comment]
There's no option to address this issue in autosuspend. The cause is that a all subscriptions are considered equally important.

I had the same problem when I started, because EPG data has not been collected yet. But after a few days, EPG data was more or less complete, and the machine went to sleep as desired. So maybe the first option for you could be to simply wait a few days.

If this doesn't help, try to tweak the following options in Tvheadend's configuration:
- Reduce the EPG scan timeout under _Configuration/Channel EPG/EPG Grabber/Over-the-air Grabbers/EPG scan timeout in seconds (30-7200)_ (e.g. set it to 600 seconds for a maximum of 10 minutes). If I remember correctly, Tvheadend stops EPG subscriptions after this amount of time.
- Grab EPG only for those channels that you're interested in. I saw in the TVheadend UI and in the logs that a lot of time was wasted for channels that I never recorded from.

Please share your experiences here.

**Comment by malvinas2** [comment]
If I understand the setting correctly the 600 seconds refer to ONE mux, but my system found 112 muxes and approx. 60 channels. But I don't know which muxes are really in use. 
Does it help to switch off the cron-job for the OTA, whose default setting is 2:04 and 14:04 o'clock every day? 
At the weekend I will have a detailed look at the log of TvH, because I imagine that there is something wrong with it (btw I am using the Satip-Server Digibit R1 with the original firmware, not the one written by perex).

**Comment by git-developer** [comment]
> Does it help to switch off the cron-job for the OTA, whose default setting is 2:04 and 14:04 o'clock every day?
I don't think so, probably the option _Force initial EPG scan at startup_ triggers EPG grabbing.

The log should show how long EPG is grabbed for each mux. EPG may then be disabled per mux (Configuration / DVB Inputs / Muxes / Edit / EPG Scan) or even per service (Configuration / DVB Inputs / Services / Edit / Ignore EPG (EIT)).

**Comment by git-developer** [comment]
I still think that the preferred solution to the problem should be found within the EPG configuration. Nevertheless I added support to suspend if only an EPG grabber is running. To try it, update to commit [`4ee6e80`](https://github.com/git-developer/autosuspend/tree/4ee6e80be7b48e3be0f9418cafdcba737446cf05) or newer and add the following line to your autosuspend configuration (`/etc/autosuspend`):
```
TVHEADEND_CONSIDER_EPGGRABBING=no
```

I appreciate your feedback.

**Comment by malvinas2** [comment]
Thank you for your support, I'll try the new version. 

I logged TvH activities using the subsystems 'EPG', 'satip', 'epggrab' and 'mpegts', but as far as I am able to judge it, everything seems to be fine. Well, it just takes several hours to update all 60 channels ;-). 

I deactivated the option 'Force initial EPG grab at start-up' which -I assume- starts the EPG grab every time the server has been started. Furthermore I changed the OTA-Cron to trigger the grabber just at 19:00 o'clock daily as this is our normal "television viewing time". 
(btw: I also installed and setup WebGrab+Plus and have got a subscription of epgdata.com, but obviously the aired information have got the most updated content)

**Comment by malvinas2** [comment]
The past few days the 'No-EPG'-feature has worked as expected, at least 'syslog' tells me that the system got suspended during a run of EPG-subscription. Thank you very much! 

One more question (I imagine it's just a small one, so I don't want to open another issue): 
The network is checked for open connections using `SAMBANETWORK='192.168.1.'` 
How do I have to modify the logit()-function, so that all found connections (=result of `smbstatus`) are written to the log-file? 
Sometimes it doesn't suspend because of open connections, but I don't know which one is still open ....

**Comment by git-developer** [comment]
Try branch [feature/samba_logging](https://github.com/git-developer/autosuspend/tree/feature/samba_logging) where I extended [IsBusy](https://github.com/git-developer/autosuspend/blob/0045376a29e6d4473c10dd7967f4710f93ca4f06/usr/local/sbin/autosuspend.sh#L48). If it doesn't work, please open a new issue.
